name       : paperkey
version    : '1.6'
release    : 3
source     :
    - https://www.jabberwocky.com/software/paperkey/paperkey-1.6.tar.gz : a245fd13271a8d2afa03dde979af3a29eb3d4ebb1fbcad4a9b52cf67a27d05f7
homepage   : https://www.jabberwocky.com/software/paperkey/
license    : GPL-2.0-or-later
component  : security
summary    : An OpenPGP key archiver
description: |
    A reasonable way to achieve a long term backup of OpenPGP (GnuPG, PGP, etc) keys is to print them out on paper. Paper and ink have long retention qualities, far longer than the magnetic or optical means that are generally used to back up computer data.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
