name       : paperkey
version    : 1.4
release    : 1
source     :
    - http://www.jabberwocky.com/software/paperkey/paperkey-1.4.tar.gz : e12bb0ec835127d12a922a8d60b3dfdb3ca8ee60bb5b4d15ae4cea85bbcf336f
license    : GPL-2.0
component  : security
summary    : An OpenPGP key archiver
description: |
    A reasonable way to achieve a long term backup of OpenPGP (GnuPG, PGP, etc) keys is to print
    them out on paper. Paper and ink have long retention qualities, far longer than the magnetic
    or optical means that are generally used to back up computer data.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
