name       : paperkey
version    : 1.5
release    : 2
source     :
    - http://www.jabberwocky.com/software/paperkey/paperkey-1.5.tar.gz : c4737943083ce92e41faf13c27a9d608105b6285c0840dfb684a7ee294142ddf
license    : GPL-2.0
component  : security
summary    : An OpenPGP key archiver
description: |
    A reasonable way to achieve a long term backup of OpenPGP (GnuPG, PGP, etc) keys is to print
    them out on paper. Paper and ink have long retention qualities, far longer than the magnetic
    or optical means that are generally used to back up computer data.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
